image: hqp6684/fuzzer
before_script:
    # do not change any of the statements in this section
    - service apache2 start
    - mysql_install_db --user=mysql -ldata=/var/lib/mysql
    - service mysql start
    - /usr/bin/mysqladmin -u root password fuzzer
    - service mysql restart
    - /mysql-setup.sh
    # do not change any of the statements in this section
samsrunner:
  script:
    # here is where you can write your commands to run your fuzzer or any custom setup commands
    - echo "hello class"
#    - ruby fuzzer.rb discover http://localhost/ --custom-auth=dvwa
    #- sudo apt-get install -y nodejs
    - npm install 
    - npm run buid
    - npm run fuzzer
  stage: test
