image: andymeneely/swen331fuzzer
before_script:
    - cat /vectors.txt
    - cat /sensitive.txt
    # do not change any of the statements in this section
    - service apache2 start
    - mysql_install_db --user=mysql -ldata=/var/lib/mysql
    - service mysql start
    - /usr/bin/mysqladmin -u root password fuzzer
    - service mysql restart
    - /mysql-setup.sh
    # do not change any of the statements in this section
samsrunnerkjj:
  script:
    # here is where you can write your commands to run your fuzzer or any custom setup commands
    - echo "hello class"
#    - ruby fuzzer.rb discover http://localhost/ --custom-auth=dvwa
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - npm install 
    - npm run discoverTest
    - npm run discoverTest2
    # - npm run test
    # - npm run fuzzer
  stage: test
